// experimental-css-on-vue/src/components/ShapePicker.vue
<script setup lang="ts">
import { ref, type Component } from "vue"
import {
  Square,
  Rectangle,
  Circle,
  Oval,
  TriangleUp,
  TriangleDown,
  TriangleLeft,
  TriangleRight,
  TriangleTopLeft,
  TriangleTopRight,
  TriangleBottomLeft,
  TriangleBottomRight,
  CurvedArrow,
  Trapezoid,
  Parallelogram,
  StarSix,
  StarFive,
  Pentagon,
  Hexagon,
  Octagon,
  Heart,
  InfinityShape,
  Diamond,
  DiamondShield,
  DiamondNarrow,
  CutDiamond,
  Egg,
  Pacman,
  TalkBubble,
  Rss,
  Burst12,
  Burst8,
  YinYang,
  BadgeRibbon,
  SpaceInvader,
  Tv,
  Chevron,
  MagnifyingGlass,
  FacebookIcon,
  Moon,
  Flag,
  Cone,
  Cross,
  Base,
  Pointer,
  Lock,
  CurvedCornerBottomLeft,
  CurvedCornerBottomRight,
  CurvedCornerTopLeft,
  CurvedCornerTopRight,
} from "./shapes"

const shapeMap = new Map<string, Component>([
  ["Square", Square],
  ["Rectangle", Rectangle],
  ["Circle", Circle],
  ["Oval", Oval],
  ["TriangleUp", TriangleUp],
  ["TriangleDown", TriangleDown],
  ["TriangleLeft", TriangleLeft],
  ["TriangleRight", TriangleRight],
  ["TriangleTopLeft", TriangleTopLeft],
  ["TriangleTopRight", TriangleTopRight],
  ["TriangleBottomLeft", TriangleBottomLeft],
  ["TriangleBottomRight", TriangleBottomRight],
  ["CurvedArrow", CurvedArrow],
  ["Trapezoid", Trapezoid],
  ["Parallelogram", Parallelogram],
  ["StarSix", StarSix],
  ["StarFive", StarFive],
  ["Pentagon", Pentagon],
  ["Hexagon", Hexagon],
  ["Octagon", Octagon],
  ["Heart", Heart],
  ["InfinityShape", InfinityShape],
  ["Diamond", Diamond],
  ["DiamondShield", DiamondShield],
  ["DiamondNarrow", DiamondNarrow],
  ["CutDiamond", CutDiamond],
  ["Egg", Egg],
  ["Pacman", Pacman],
  ["TalkBubble", TalkBubble],
  ["Rss", Rss],
  ["Burst12", Burst12],
  ["Burst8", Burst8],
  ["YinYang", YinYang],
  ["BadgeRibbon", BadgeRibbon],
  ["SpaceInvader", SpaceInvader],
  ["Tv", Tv],
  ["Chevron", Chevron],
  ["MagnifyingGlass", MagnifyingGlass],
  ["FacebookIcon", FacebookIcon],
  ["Moon", Moon],
  ["Flag", Flag],
  ["Cone", Cone],
  ["Cross", Cross],
  ["Base", Base],
  ["Pointer", Pointer],
  ["Lock", Lock],
  ["CurvedCornerBottomLeft", CurvedCornerBottomLeft],
  ["CurvedCornerBottomRight", CurvedCornerBottomRight],
  ["CurvedCornerTopLeft", CurvedCornerTopLeft],
  ["CurvedCornerTopRight", CurvedCornerTopRight],
])

const shapeNames = Array.from(shapeMap.keys())

const shapeComponents = ref<Component[]>([])

function handleShapeChange(event: Event) {
  const select = event.target as HTMLSelectElement
  const selectedOptions = Array.from(select.selectedOptions).map((option) => option.value)
  const components: Component[] = []
  for (const option of selectedOptions) {
    const component = shapeMap.get(option)
    if (component) {
      components.push(component)
    }
  }
  shapeComponents.value = components
}
</script>

<template>
  <div>
    <label for="selectShape">Choose shapes:</label>
    <select id="selectShape" multiple size="4" @change="handleShapeChange">
      <option v-for="name in shapeNames" :key="name" :value="name">{{ name }}</option>
    </select>
    <component :is="comp" v-for="(comp, index) in shapeComponents" :key="index" />
  </div>
</template>

// experimental-ui-on-angular/src/app/components/css/shape-picker/shape-picker.ts
import { Component, signal } from "@angular/core"
import { Shape as ShapeComponent } from "@/app/components/shape/shape"

interface Shape {
  label: string
  id: string
}

@Component({
  selector: "app-shape-picker",
  standalone: true,
  imports: [ShapeComponent],
  templateUrl: "./shape-picker.html",
})
export class ShapePicker {
  readonly shapes: readonly Shape[] = [
    { label: "Square", id: "square" },
    { label: "Rectangle", id: "rectangle" },
    { label: "Circle", id: "circle" },
    { label: "Oval", id: "oval" },
    { label: "TriangleUp", id: "triangle-up" },
    { label: "TriangleDown", id: "triangle-down" },
    { label: "TriangleLeft", id: "triangle-left" },
    { label: "TriangleRight", id: "triangle-right" },
    { label: "TriangleTopLeft", id: "triangle-top-left" },
    { label: "TriangleTopRight", id: "triangle-top-right" },
    { label: "TriangleBottomLeft", id: "triangle-bottom-left" },
    { label: "TriangleBottomRight", id: "triangle-bottom-right" },
    { label: "CurvedArrow", id: "curved-arrow" },
    { label: "Trapezoid", id: "trapezoid" },
    { label: "Parallelogram", id: "parallelogram" },
    { label: "StarSix", id: "star-six" },
    { label: "StarFive", id: "star-five" },
    { label: "Pentagon", id: "pentagon" },
    { label: "Hexagon", id: "hexagon" },
    { label: "Octagon", id: "octagon" },
    { label: "Heart", id: "heart" },
    { label: "InfinityShape", id: "infinity" },
    { label: "Diamond", id: "diamond" },
    { label: "DiamondShield", id: "diamond-shield" },
    { label: "DiamondNarrow", id: "diamond-narrow" },
    { label: "CutDiamond", id: "cut-diamond" },
    { label: "Egg", id: "egg" },
    { label: "Pacman", id: "pacman" },
    { label: "TalkBubble", id: "talk-bubble" },
    { label: "Rss", id: "rss" },
    { label: "Burst12", id: "burst-12" },
    { label: "Burst8", id: "burst-8" },
    { label: "YinYang", id: "yin-yang" },
    { label: "BadgeRibbon", id: "badge-ribbon" },
    { label: "SpaceInvader", id: "space-invader" },
    { label: "Tv", id: "tv" },
    { label: "Chevron", id: "chevron" },
    { label: "MagnifyingGlass", id: "magnifying-glass" },
    { label: "FacebookIcon", id: "facebook-icon" },
    { label: "Moon", id: "moon" },
    { label: "Flag", id: "flag" },
    { label: "Cone", id: "cone" },
    { label: "Cross", id: "cross" },
    { label: "Base", id: "base" },
    { label: "Pointer", id: "pointer" },
    { label: "Lock", id: "lock" },
    { label: "CurvedCornerBottomLeft", id: "curved-corner-bottom-left" },
    { label: "CurvedCornerBottomRight", id: "curved-corner-bottom-right" },
    { label: "CurvedCornerTopLeft", id: "curved-corner-top-left" },
    { label: "CurvedCornerTopRight", id: "curved-corner-top-right" },
  ]

  readonly selectedShapes = signal<Shape[]>([])

  onSelectionChange(event: Event): void {
    const select = event.target as HTMLSelectElement

    this.selectedShapes.set(
      Array.from(select.selectedOptions).map((option) =>
        this.shapes.find((shape) => shape.label === option.value)!,
      ),
    )
  }
}
